import Breadcrumbs from "@/components/ui/breadcrumbs";
import {
  TypographyH1,
  TypographyH2,
  TypographyH3,
  TypographyP,
} from "@/components/ui/typography";
import Link from "next/link";

export default async function Page() {
  return (
    <>
      <Breadcrumbs />
      <TypographyH1>Managing the Crew</TypographyH1>
      <TypographyH2>Tier</TypographyH2>
      <TypographyP>
        The crew's tier represents the total capability of the crew as a
        faction, not the raw number of people in it. Though the crew has no
        single leader, its tier is increased just like any other{" "}
        <Link href="/game/arc-three/rules/time-passes/managing-a-faction">
          <b className="text-red-500">
            <u>faction</u>
          </b>
        </Link>
        . Any member of the crew may spend <b>rep</b> to increase the crew's
        tier.
      </TypographyP>
      <TypographyH2>Resources</TypographyH2>
      <TypographyP>
        The crew gains resources with the ebb and flow of Fabrication just like
        other factions do. Except for the theft, violence, and extortion. Well,
        maybe the other factions are doing that too. Unlike other factions, the
        crew has a discrete amount of each resource it can store.
      </TypographyP>
      <TypographyP>
        When <b>time passes</b>, those stored resources get evenly distributed
        amongst the crew's members. If there isn't enough to go around, the ones
        left out of this cycle are prioritized in the next.
      </TypographyP>
      <TypographyH3>Manpower</TypographyH3>
      <TypographyP>
        All <b>manpower</b> generated by the crew's tier is evenly distributed
        amongst the crew's <b>Operatives</b>.
      </TypographyP>
      <TypographyH2>Alliances</TypographyH2>
      <TypographyP>
        The crew's alliances are handled just like any other{" "}
        <Link href="/game/arc-three/rules/time-passes/managing-a-faction">
          <b className="text-red-500">
            <u>faction's</u>
          </b>
        </Link>
        .
      </TypographyP>
      <TypographyH2>Projects</TypographyH2>
      <TypographyP>
        The crew's projects are listed{" "}
        <Link href="game/arc-three/play#crew">
          <b className="text-red-500">
            <u>here</u>
          </b>
        </Link>
        . And more coming soon.
      </TypographyP>
    </>
  );
}
